<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%tweet}}".
 *
 * @property integer $id
 * @property integer $twitter_user_id
 * @property string $twitter_tweet_id
 * @property string $text
 * @property string $media_url
 * @property string $media_url_https
 * @property string $type
 * @property integer $retweet_count
 * @property integer $favorite_count
 * @property double $tweet_dt
 * @property double $created_dt
 * @property double $updated_dt
 *
 * @property TwitterDetail $twitterUser
 */
class Tweet extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%tweet}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['twitter_user_id', 'twitter_tweet_id', 'tweet_dt'], 'required'],
            [['twitter_user_id', 'retweet_count', 'favorite_count'], 'integer'],
            [['text', 'media_url', 'media_url_https'], 'string'],
            [['tweet_dt', 'created_dt', 'updated_dt'], 'number'],
            [['twitter_tweet_id'], 'string', 'max' => 30],
            [['type'], 'string', 'max' => 15],
            [['twitter_user_id'], 'exist', 'skipOnError' => true, 'targetClass' => TwitterDetail::className(), 'targetAttribute' => ['twitter_user_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'twitter_user_id' => 'Twitter User ID',
            'twitter_tweet_id' => 'Twitter Tweet ID',
            'text' => 'Text',
            'media_url' => 'Media Url',
            'media_url_https' => 'Media Url Https',
            'type' => 'Type',
            'retweet_count' => 'Retweet Count',
            'favorite_count' => 'Favorite Count',
            'tweet_dt' => 'Tweet Dt',
            'created_dt' => 'Created Dt',
            'updated_dt' => 'Updated Dt',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTwitterUser()
    {
        return $this->hasOne(TwitterDetail::className(), ['id' => 'twitter_user_id']);
    }

    public function beforeSave($insert)
    {
        if($insert) {
            $this->created_dt = time();
            $this->updated_dt = 0;
        }   else    {
            $this->updated_dt = time();
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
